# Generated by Django 4.1.2 on 2022-11-29 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='pictureOfPaper',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
